apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:

  name: argo-application

  namespace: guestbook

spec:

  project: default

  source:
    
    repoURL: https://github.com/ravikumara004/sample_test_repo.git
    
    targetRevision: main

    path: project/poc

  destination: 

    server: https://kubernetes.default.svc

    namespace: guestbook

  syncPolicy:

    syncOptions:

    - CreateNamespace=true

    automated:

      selfHeal: true

      prune: true
