apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:

  name: argo-application

  namespace: guestbook

spec:

  project: default

  source:
    
    repoURL: https://gitlab.com/jasmine.harit/argocd-app-config.git
    
    targetRevision: main

    path: boostrap/project

  destination: 

    server: https://kubernetes.default.svc

    namespace: guestbook

  syncPolicy:

    syncOptions:

    - CreateNamespace=true

    automated:

      selfHeal: true

      prune: true
