apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - git:
      repoURL: https://github.com/ravikumara004/sample_test_repo.git
      revision: main
      directories:
        - path: boostrap/project/*
  template:
    metadata:
      name: 'appset-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/ravikumara004/sample_test_repo.git
        targetRevision: main
        path: boostrap/project/*
      destination:
        server: '{{url}}'
        namespace: guestbook
