apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-poc
spec:
  generators:
  - list:
      elements:
      - cluster: engineering-dev-poc
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-guestbook-poc'
    spec:
      project: default
      source:
        repoURL: https://github.com/ravikumara004/sample_test_repo.git
        targetRevision: main
        path: project/poc
      destination:
        server: '{{url}}'
        namespace: poc
